@startuml
title Добавление начисления сотруднику

start
:Ввод: выбор сотрудника;
:Вывд: список начислений данному сотруднику;
:Ввод: добавить начисление;
:Вывод: все виды начилений;
label input_date
:Ввод: дата начисления;
if (Планируется ли уже выбранное начисление в выбранном месяце?) then (да)
    :Вывод: начисление уже планируется;
    goto input_date
else (нет)
    :Ввод: размер начисления;
    :Фиксация данных о планируемой выплате;
endif 

stop