@startuml
title Регистрация сотрудника

start
label input
:Ввод: логин и пароль;

if (Такой логин уже существует?) then (Да)
    :Вывод: логин занят, выберите другой;
    goto input
else (нет)
    :Сохранение данных пользователя;
    :Вывод: регистрация выполнена;
endif
stop
@enduml
